export default {
    list: [{
            id: '1',
            name: "16春计网专（1）班",
            count: 50,
            complete_count: 49,
            allow: 0,
        },
        {
            id: '1',
            name: "16春计网专（1）班",
            count: 50,
            complete_count: 49,
            allow: 1,
        },
        {
            id: '1',
            name: "16春计网专（1）班",
            count: 50,
            complete_count: 49,
            allow: 1,
        },
        {
            id: '1',
            name: "16春计网专（1）班",
            count: 50,
            complete_count: 49,
            allow: 1,
        },
        {
            id: '1',
            name: "16春计网专（1）班",
            count: 50,
            complete_count: 49,
            allow: 1,
        },
        {
            id: '1',
            name: "16春计网专（1）班",
            count: 50,
            complete_count: 49,
            allow: 1,
        },
        {
            id: '1',
            name: "16春计网专（1）班",
            count: 50,
            complete_count: 49,
            allow: 1,
        },
        {
            id: '1',
            name: "16春计网专（1）班",
            count: 50,
            complete_count: 49,
            allow: 1,
        },
        {
            id: '1',
            name: "16春计网专（1）班",
            count: 50,
            complete_count: 49,
            allow: 1,
        },
        {
            id: '1',
            name: "16春计网专（1）班",
            count: 50,
            complete_count: 49,
            allow: 1,
        },
        {
            id: '1',
            name: "16春计网专（1）班",
            count: 50,
            complete_count: 49,
            allow: 1,
        },
        {
            id: '1',
            name: "16春计网专（1）班",
            count: 50,
            complete_count: 49,
            allow: 1,
        },
        {
            id: '1',
            name: "16春计网专（1）班",
            count: 50,
            complete_count: 49,
            allow: 1,
        },
        {
            id: '1',
            name: "16春计网专（1）班",
            count: 50,
            complete_count: 49,
            allow: 1,
        },
    ],
    total: 0,
    current_page: 1,
    per_page: 10,
    page_sizes: [10, 20, 30, 40, 50, 60],
    search_keyword: [],
    search_data: {},
}