export default {
    list: [{
            id: '1111',
            name : "16春计网专（1）班",
            count : 50,
            complete_count : 49,
            allow : 1,
        },
        {
            id: '1',
            name : "16春计网专（1）班",
            count : 50,
            complete_count : 49,
            allow : 0,
        },
        {
            id: '1',
            name : "16春计网专（1）班",
            count : 50,
            complete_count : 49,
            allow : 1,
        },
        {
            id: '1',
            name : "16春计网专（1）班",
            count : 50,
            complete_count : 49,
            allow : 1,
        },
        {
            id: '1',
            name : "16春计网专（1）班",
            count : 50,
            complete_count : 49,
            allow : 1,
        },
    ],
    total: 0,
    pageIndex: 1,
    pageSize: 10,
    pageSizes: [10, 20, 30, 40, 50, 60],
    searchKeyword: [],
    searchData: {},
}